blog/urls.py
from django.urls import path
from . import views


app_name = "blog"
urlpatterns = [
    path('detail/<slug:slug>' , views.post_detail , name="article_detail"),
    path('list' , views.article_list , name="articles_list"),
    path('category/<int:pk>' , views.category_detail , name="category_detail"),
    path('search/' , views.search , name="search_articles"),
    path('contactus' , views.contactus , name="contact_us"),
    # path('testbase' , views.TestBaseView.as_view() , name="test_base"),
    path('users' , views.UserList.as_view() , name="user_list"),
    path('red' , views.HomePageRedirect.as_view() , name="redirect"),
]

home/urls.py
from django.urls import path
from . import views

app_name = "home"
urlpatterns = [
    path("" , views.home , name="main"),
    path('sidebar' , views.sidebar , name="sidebar_partial")
]

standblog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('home.urls')),
    path('' , include('account.urls')),
    path('articles/' , include('blog.urls')),
]
urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_URL)

home/views.py
from django.shortcuts import render , redirect
from blog.models import Article
from django.urls import reverse

# Create your views here.

def home(request):
    articles = Article.objects.all()
    recent_articles = Article.objects.all().order_by('-created')[:3]
    return render(request , "home/index.html" , {'articles':articles })


def sidebar(request):
    data = {'name':'shadman'}
    return render(request , 'includes/sidebar.html' , context=data)

home/templates/home/index.html
{% extends 'base.html' %}
{% load static %}
{% load render_partial %}
{% load social_share %}
{% load filters %}
{% load my_template_tags %}
{% block title %}
    home
{% endblock %}

{% block content %}
    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="main-banner header-text">
        <div class="container-fluid">
            <div class="owl-banner owl-carousel">
                {% for article in articles %}
                    <div class="item">
                        <img src="{{ article.image.url }}" alt="{{ article.title}">
                                <div class="item-content">
                                <div class="main-content">
                                <div class="meta-category">
                                <span>{{ article.category.all.0 }}</span>
                        </div>
{#                        <a href="{% url "blog:article_detail" article.id %}"><h4>{{ article.title }}</h4></a>#}
                        <a href="{{ article.get_absolute_url }}"><h4>{{ article.title }}</h4></a>
                        <ul class="post-info">
                            <li><a href="#">{{ article.author.username }}</a></li>
                            <li><a href="#">{{ article.created }}</a></li>
                            <li><a href="#">12 Comments</a></li>
                        </ul>
                    </div>
                    </div>
                    </div>
                {% endfor %}
    </div>
    </div>
    </div>
    <!-- Banner Ends Here -->

    <section class="call-to-action">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="main-content">
                        <div class="row">
                            <div class="col-lg-8">
                                <span>{% current_time "%Y-%m-%d" %}</span>
                                <h4>{% show_result "shadman" %}</h4>
                            </div>
                            <div class="col-lg-4">
                                <div class="main-button">
                                    <a rel="nofollow" href="https://templatemo.com/tm-551-stand-blog" target="_parent">Download
                                        Now!</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <section class="blog-posts">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="all-blog-posts">
                        <div class="row">
                            {% for article in recent_articles %}
                                <div class="col-lg-12">
                                    <div class="blog-post">
                                        <div class="blog-thumb">
                                            <img src="{{ article.image.url }}" alt="">
                                        </div>
                                        <div class="down-content">
                                            <span>Lifestyle</span>
                                            <a href="post-details.html"><h4>{{ article.title }}</h4></a>
                                            <ul class="post-info">
                                                <li><a href="#">{{ article.author.get_full_name }}</a></li>
                                                <li><a href="#">{{ article.created }}</a></li>
                                                <li><a href="#">12 Comments</a></li>
                                            </ul>
                                            <p>{{ article.body|truncatewords:30 }}</p>
                                            <div class="post-options">
                                                <div class="row">
                                                    <div class="col-6">
                                                        <ul class="post-tags">
                                                            <li><i class="fa fa-tags"></i></li>
                                                            <li><a href="#">{{ article.category.all.0 }}</a></li>
                                                        </ul>
                                                    </div>
                                                    <div class="col-6">
                                                        <ul class="post-share">
                                                            <li><i class="fa fa-share-alt"></i></li>
                                                            <li>{% post_to_whatsapp article.get_absolute_url "whatsapp" %}</li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                            <div class="col-lg-12">
                                <div class="main-button">
                                    <a href="{% url "blog:articles_list" %}">View All Articles</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% render_partial "home:sidebar_partial" %}
            </div>
        </div>
    </section>

{% endblock %}

home/templates/home/result.html
<p>{{ text }}</p>